version: "3.9"
services:
  engine:
    build: ./engine
    ports:
      - "8000:8000"
    environment:
      # point to converter root endpoint (octet-stream)
      - DWG2DXF_URL=http://converter:8080/
    depends_on:
      - converter

  converter:
    build: ./converter_service
    ports:
      - "8080:8080"
    environment:
      - ODA_FILECONVERTER_BIN=/opt/oda/ODAFileConverter
      - ODA_DXF_VERSION=ACAD2018
    volumes:
      # put ODA File Converter here (download yourself)
      - ./ODAFileConverter:/opt/oda:ro
